### ISSUE TITLE
Zabbix 4.0 template import fails: prototype contains item prototypes from multiple discovery rules

### ISSUE THREAD

**Issue by yantsa** [rvalitov/zabbix-php-fpm#22]
Thanks for you great work . I am trying to import the template from latest stable version on Zabbix 4.0.17. The error I get is : 

Graph prototype "Pool {#POOLNAME} Memory" contains item prototypes from multiple discovery rules.

any help is much appreciated .

**Comment by yantsa** [comment]
sorry for this "stupid" question. It's a zabbix issue.

**Comment by rvalitov** [comment]
Hi! That's an interesting situation. Please share your knowledge:

-  What was the reason of the problem? There was a conflict with some other template?
- How did you solve it?

I think this information may be helpful if other users face the same problem. Thank you!

**Comment by rvalitov** [comment]
It seems this error happens when you have another template with the same name of items, prototypes, etc. A solution is to use `Delete and Clear` button on the former template as described [here](https://www.zabbix.com/forum/zabbix-help/49396-item-procotols-from-multiple-sources-preventing-tigger-prototype-creation). Using `Delete` only button is not enough. The Wiki was updated with description of this case.

@yantsa if you have any feedback and comments here, please kindly share it. Thank you!

**Comment by yantsa** [comment]
Sorry for my delayed response. Yes confirmed ,  that was exactly my case.
