### ISSUE TITLE
Gave this a good effort. Didn't work. 

### ISSUE THREAD

**Issue by haydenjames** [rvalitov/zabbix-php-fpm#57]
Thanks for your time on this. 

Wiki states: 
> Extract the XML template file from the archive that corresponds to your version of Zabbix server.

But the downloaded zip (both stable and dev) only contain. **zabbix_php_fpm_template_4.0.xml**

I'm on 5.0. Import screen was not the same. Tired to import with default options. The result:
> No permissions to referred object or it does not exist!

Ubuntu 18.04 + Zabbix 5.0 LTS

**Comment by rvalitov** [comment]
@haydenjames Hi James!
The name `zabbix_php_fpm_template_4.0.xml` works for 5.0 also. There's no any separate file for 5.0.
Did you install any other PHP-FPM templates for Zabbix? Because there's a chance that there was a conflict in the name of the template being imported if you already had a template with a similar name already installed.

Can you please post a full error log of the template import failure? Instructions how to get this log is here https://github.com/rvalitov/zabbix-php-fpm/wiki/Testing-and-Troubleshooting#1-template-import-failure-on-zabbix-server
