### ISSUE TITLE
zabbix 4.4 support

### ISSUE THREAD

**Issue by sleptor** [rvalitov/zabbix-php-fpm#7]
After template importing Zabbix shows "Not supported (Unsupported item key)"

Are you going to add 4.4 support?

**Comment by rvalitov** [comment]
Yes I plan to work with Zabbix 4.4 after I return from vacation in December.

**Comment by pbousek** [comment]
I run zabbix 
zabbix_server -V
zabbix_server (Zabbix) 4.4.1
Revision 8870606e6a 28 October 2019, compilation time: Oct 28 2019 13:46:36

and template was imported succesfuly without any error.
But there is probably some issue, because both shell scripts seems to work (return pools and pool information) but only number of cpus is shown under php-fpm.

**Comment by rvalitov** [comment]
@sleptor, I added a section [How to troubleshoot template import failure](https://github.com/rvalitov/zabbix-php-fpm#how-to-troubleshoot-template-import-failure) in README. Please, follow it, and provide more details here.

**Comment by rvalitov** [comment]
@pbousek when Zabbix agent reports continuously many errors, then Zabbix server can make a decision to disable the fields that report the errors. Please, check in the configuration of your host all the fields, and re-enable them (including the discovery rule) if necessary. Zabbix server log file should also provide more details if there are still any errors exist that should be fixed.

**Comment by pbousek** [comment]
@rvalitov but whats wrong when
./zabbix_php_fpm_discovery.sh 
{"data":[{"{#POOLNAME}":"default"
,"{#POOLSOCKET}":"localhost:8001"
}]}

and
./zabbix_php_fpm_status.sh localhost:8001 /php-fpm-status
{"pool":"default","process manager":"dynamic","start time":1574796621,"start since":1032,"accepted conn":263,"listen queue":0,"max listen queue":0,"listen queue len":511,"idle processes":9,"active processes":1,"total processes":10,"max active processes":1,"max children reached":0,"slow requests":0}
output of both scripts seems ok, but the data are not visible in zabbix, zabbix-server doesn't contain errors related to this

**Comment by rvalitov** [comment]
@pbousek yes, the output of both scripts look good. Currently I have no idea why Zabbix does not gather the data...

I recommend to use `zabbix_get` utility from the Zabbix server console to check that the Zabbix server really can access your host and get information from there.

**Comment by pbousek** [comment]
@rvalitov  i got only empty value for discover
{"data":[]}

could be the issue the last sentence? I have AllowRoot enabled as described in readme, but ...
### Option: AllowRoot
#       Allow the agent to run as 'root'. If disabled and the agent is started by 'root', the agent
#       will try to switch to the user specified by the User configuration option instead.
#       **Has no effect if started under a regular user.**

**Comment by pbousek** [comment]
@rvalitov it seems that when you run zabbix under zabbix user (default) than you cannot user AllowRoot option and you are not able to see output of the script

**Comment by rvalitov** [comment]
Yes, Zabbix agent must run under root, it's specified in README.

**Comment by pbousek** [comment]
@rvalitov i did some crazy sudo hack and it works although zabbix run under zabbix user, but I'm not so happy with this "game" with root privileges...

**Comment by rvalitov** [comment]
@pbousek unfortunately detection of running PHP-FPM processes requires root or sudo. No other way. If you have a better solution that can avoid using root, then please let me know!

**Comment by pbousek** [comment]
OK, if someone doesn't want to run zabbix_agent as root,  it's possible to add to
/etc/sudoers
zabbix ALL = NOPASSWD: /etc/zabbix/zabbix_php_fpm_discovery.sh

and change
userparameter_php_fpm.conf
add sudo to this line
UserParameter=php-fpm.discover,sudo /etc/zabbix/zabbix_php_fpm_discovery.sh

it should be enough and you run only one script as root instead of running whole agent and all scripts

**Comment by rvalitov** [comment]
@pbousek thank you for your contribution! I will update the README.
So, now everything works fine for you with Zabbix 4.4?

**Comment by pbousek** [comment]
@rvalitov yes, everything works now on zabbix 4.4.1
Only thing that is little bit disturbing is flapping of "PHP-FPM uses queue on {HOST.NAME} pool {#POOLNAME}" trigger when you use php-fpm pool with "ondemand" - probably when there is no traffic, no process is started and expression with diff()}=1 is evaluated as problem. I disabled this trigger.

**Comment by rvalitov** [comment]
Thank you for the info! Can you please make a new issue about the ondemand trigger?

**Comment by rvalitov** [comment]
I'm closing this issue.
@sleptor please try again with the latest version of this template. If still it does not work, then follow the troubleshooting section of the updated README and post more details here.

**Comment by rvalitov** [comment]
Recently tested with Zabbix 4.4, works fine. Environment details:
```console
root@Debian10:/# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
root@Debian10:/# apt-cache policy zabbix-server-mysql
zabbix-server-mysql:
  Installed: 1:4.4.4-1+buster
  Candidate: 1:4.4.4-1+buster
  Version table:
 *** 1:4.4.4-1+buster 500
        500 http://repo.zabbix.com/zabbix/4.4/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
     1:4.0.4+dfsg-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
```
